### PR TITLE
Angular 17 support

### PR DESCRIPTION
**Pull request by Quentigus**
- Angular 17
- New standalone demo (previous demo was broken)

### CODE REVIEW

**Comment by evilaliv3** [comment]
Oh, sorry @Quentigus  i did not notice this pull request.

Do you consider the work ready for integration or do you still miss to implement/test something?

\cc @msmannan00

**Comment by sebastiencl** [comment]
Hi. When do you think PR will be merge?

**Comment by MaewenPelletier** [comment]
Hello ! 

Thanks for the update, any release date please ?

**Comment by evilaliv3** [comment]
Proceeding with the merge and the release! Sorry for the delay.

**Comment by sebastiencl** [comment]
Perfect. Thanks :)

**Pull request merged**
