### PR TITLE
Add support  Angular 16

### PR DESCRIPTION
**Pull request by Hilario-Rodriguez**

### CODE REVIEW

**Comment by eneajaho** [comment]
Hello @MartinNuc 
Can we merge this one?

**Comment by driatvak** [comment]
Hey @MartinNuc, we would this need to be merged 🙏

**Comment by evilaliv3** [comment]
@Hilario-Rodriguez @itsaplev : would you like me to proceed releasing the npm pagage for 0.7.0 ?

**Comment by evilaliv3** [comment]
@Hilario-Rodriguez : Is it possible for you to update the library to support Angular 17?

**Pull request merged**
