### PR TITLE
Add angular 13 support

### PR DESCRIPTION
**Pull request by itsaplev**

### CODE REVIEW

**Comment by itsaplev** [comment]
@AidasK @evilaliv3 @MartinNuc 
Hello, could you please check this PR

**Comment by AidasK** [comment]
@MartinNuc can you review and merge this if all is ok?

**Comment by itsaplev** [comment]
@MartinNuc gentle reminder

**Comment by itsaplev** [comment]
@AidasK @MartinNuc gentle reminder 2

**Comment by MartinNuc** [comment]
@itsaplev sorry for noticing this so late 🙈Going to merge it.

Thank you so much for the contribution! 🚀

**Review by MartinNuc — APPROVED** [review]

**Comment by itsaplev** [comment]
@AidasK @MartinNuc Thank you Martin! Could you please merge this pr and update NPM package?

**Comment by AidasK** [comment]
@MartinNuc Can you merge this and publish a new release? Thanks!

**Comment by itsaplev** [comment]
> Anyone wants maintainer permissions to release this? It looks like @MartinNuc could use some help

I can try

**Comment by AidasK** [comment]
Added, have fun @itsaplev :))

**Comment by AidasK** [comment]
If you have any questions, don't hesitate to ask. I am not really familiar with angular, so that's why I am not taking this on myself. As for release, normal approach would be to release this as a new major version, such as v0.5.0 or even v1.0.0. Please don't release it on 0.4x as it might break things for others.

**Comment by itsaplev** [comment]
@AidasK  Ok! Thank you

**Comment by itsaplev** [comment]
@AidasK I released 0.5.0, could you please update npm package?

**Comment by AidasK** [comment]
hmm, anyone knows how to publish this on https://www.npmjs.com/package/@flowjs/ngx-flow ? Ran npm publish, and it was published to https://www.npmjs.com/package/ngx-flow instead

**Comment by AidasK** [comment]
Anyway, did this, ran it again and it happened. https://github.com/flowjs/ngx-flow/commit/fa6a5e9f6baaba0933b242b75041896be8b35786

Please double check if it's now working with angular 13

**Comment by AidasK** [comment]
Not sure why https://app.travis-ci.com/github/flowjs/ngx-flow/builds/249973163 fails

@itsaplev can you confirm that `npm run test` command works for you?

**Comment by itsaplev** [comment]
@AidasK yes, there is missing test plugin in package.json I will fix it now

**Comment by itsaplev** [comment]
@AidasK about failed build, I've checked locally, it is really failed with this version of yarn 1.3.2 but it is ok with latest 1.12.18. We need to update yarn somehow at travis

**Pull request merged**
