### PR TITLE
Add travis CI

### PR DESCRIPTION
**Pull request by MartinNuc**
@AidasK I think I will need proper URL's for badges in `README.md` (currently pointing to my repo travis) and CC_TEST_REPORTER_ID (for code coverage from https://codeclimate.com)

### CODE REVIEW

**Comment by AidasK** [comment]
Do you need some permissions from me for a proper URL?

**Comment by MartinNuc** [comment]
@AidasK I dont see flowjs at my Travis Account:

screen shot 2018-09-11 at 14 12 02

Although I can see flowjs organisation in my Github account:

screen shot 2018-09-11 at 14 12 58

Tried to Sync account and link on the bottom `Review and add your authorized organizations.` which leads me to Travis CI app where I see flowjs present.

Can you take a look in your Travis CI if there is `ngx-flow` repository, please?

**Comment by MartinNuc** [comment]
@AidasK I saw you use Travis and codeclimate on `ng-flow` so I made configuration for these but I guess you have to setup it up.

**Comment by AidasK** [comment]
I have invited you to flowjs team, so you should be able to see it on travis. I have also enabled builds for ngx-flow project (just pressed enable, nothing much, but hope it is enough).

**Comment by MartinNuc** [comment]
I can see this repo now in Travis CI. I will merge to put travis CI config to the master branch and finish badge configuration later.

**Comment by MartinNuc** [comment]
Actually no changes were required. It just works :-) Thanks

**Comment by AidasK** [comment]
[Maintainability](https://codeclimate.com/github/flowjs/ngx-flow/maintainability)

[Test Coverage](https://codeclimate.com/github/flowjs/ngx-flow/test_coverage)

Generated!

**Comment by AidasK** [comment]
TEST REPORTER ID:
3868b078bd767a7c54dbb77c6b7e427ef0da3421dae1b643bfd0b41106cd4774

image
image

**Comment by MartinNuc** [comment]
@AidasK contact me please on twitter https://twitter.com/martin_nuc :)

**Pull request merged**
