### PR TITLE
Update package.json @types/flowjs for bugfix

### PR DESCRIPTION
**Pull request by SamLukins**
Mainly for this bug fix commit that fixes some event types https://github.com/DefinitelyTyped/DefinitelyTyped/commit/13a134561d8a25f3dbde80e917fd092597fd31a7#diff-6bbc52ce72760d697dfc6fcda362ac80

### CODE REVIEW

**Comment by MartinNuc** [comment]
I will release a new version later today or tomorrow.

**Comment by SamLukins** [comment]
Is there going to be an update to the npm package at some point?

**Comment by MartinNuc** [comment]
When I opened the repo today I saw there commit with version bump but didn't remember this one 🙈 I will do it today.

**Comment by MartinNuc** [comment]
@SamLukins should be now published in 0.4.4

**Pull request merged**
